#!/usr/bin/env python3
"""Build student_survey.json and pedagog_survey.json from raw docx text."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

MATRIX_FREQ_COLS = [
    "Har kuni",
    "Haftasiga 5–6 kun",
    "Haftasiga 3–4 kun",
    "Haftasiga 1–2 kun",
    "Kamdan-kam",
    "Hech qachon",
]
MATRIX_FOOD_COLS = [
    "Kuniga bir martadan ko'p",
    "Kuniga 1 marta",
    "Haftasiga 2–3 marta",
    "Haftasiga 1 marta",
    "Kamdan-kam",
    "Hech qachon",
]
MATRIX_PREP_COLS = [
    "Har oy",
    "Yiliga 4–6 marta",
    "Yiliga 2 marta",
    "Kamdan-kam",
    "Faqat kasallanganda",
    "Hech qachon",
]
SYMPTOM_ROWS = [
    "Bosh og'rishi",
    "Yig'loqilik, kayfiyatning tez-tez o'zgarishi, qo'rquvlar",
    "Ish smenasidan keyin kuchsizlanish, charchash",
    "Ortib borayotgan asabiylik (tez jahllanish)",
    "Ishdan keyin odamlar bilan muloqot qilish istagining yo'qligi",
    "Uyquning buzilishi",
    "Ko'p terlash",
    "Bosh aylanishi",
    "Hushdan ketish holatlari",
    "Harakatsizlikda o'tirib turolmaslik, ortiqcha bezovtalik",
    "Shishlar (oteklar)",
    "Yurak sohasida og'riq, noqulaylik, yurak urishining tezlashishi yoki uzilishlari",
    "Arterial bosimning ko'tarilishi",
    "Tez-tez burun oqishi (yiliga 4 martadan ko'p)",
    "Tez-tez yo'tal (yiliga 4 martadan ko'p)",
    "Tez-tez tomoq og'rig'i, xirillash, ovozning yo'qolishi (yiliga 4 martadan ko'p)",
    "Qorin og'rig'i",
    "Ko'ngil aynishi, jig'ildon qaynashi, kekirish",
    "Ich qotishi",
    "Ich ketishi",
    "Bel og'rig'i",
    "Peshob chiqarishda og'riq yoki achishish",
    "Allergiya: oziq-ovqat, hidlar, gullar, chang, dorilar, hayvon yungi (shish, nafas qiyinlashi, toshma)",
    "Tish og'rig'i",
]
MEAL_ROWS = [
    "Uyda nonushta qilaman",
    "OTMda nonushta qilaman",
    "Uyda tushlik qilaman",
    "OTMda tushlik qilaman",
    "Kechki ovqat qilaman",
]
FOOD_ROWS = [
    "Don mahsulotlari (grechka, guruch va boshqalar)",
    "Sut",
    "Tvorog",
    "Pishloq",
    "Go'sht (mol, cho'chqa, qo'y)",
    "Kolbasa, sosiska",
    "Baliq",
    "Sabzavotlar",
    "Kartoshka",
    "Mevalar",
    "Sharbat",
    "Tuxum",
    "Makaron mahsulotlari",
    "Shirinliklar (konfet, pirojniy)",
]
PREP_ROWS = [
    "Vitaminlar",
    "Vitamin va mikroelement komplekslari",
    "Biologik faol qo'shimchalar (BAA/BAD)",
]


def q(id_, text, options, section="", type_="single_choice", rows=None, columns=None, description=None):
    return {
        "id": id_,
        "text": text,
        "options": options or [],
        "section": section,
        "type": type_,
        "rows": rows or [],
        "columns": columns or [],
        "description": description,
    }


def build_student():
    questions = [
        q(1, "Yoshingiz", [], "Umumiy ma'lumot", "text"),
        q(2, "Jinsingiz", ["Erkak", "Ayol"], "Umumiy ma'lumot"),
        q(3, "Kursingiz", ["1", "2", "3", "4", "5", "6"], "Umumiy ma'lumot"),
        q(4, "Fakultetingiz", [], "Umumiy ma'lumot", "text"),
        q(5, "Yashash sharoitingiz", ["Yotoqxona", "Ijara uy", "Oila bilan"], "O'quv va yashash"),
        q(6, "Yashash sharoiti sog'ligingizga ta'sir qiladimi?", ["Ha", "Yo'q", "Ba'zan"], "O'quv va yashash"),
        q(7, "O'quv yuklamasi darajasi", ["Yuqori", "O'rta", "Past"], "O'quv va yashash"),
        q(8, "O'quv yuklamasi stressga sabab bo'ladimi?", ["Ha", "Yo'q", "Ba'zan"], "O'quv va yashash"),
        q(9, "Jismoniy faollik bilan shug'ullanasizmi?", ["Har kuni", "Haftada 2–3 marta", "Kam", "Yo'q"], "Jismoniy faolllik"),
        q(10, "Qaysi turdagi faolllik?", ["Yugurish", "Fitnes", "Sport o'yinlari", "Yo'q"], "Jismoniy faolllik"),
        q(11, "Kunlik harakat (piyoda yurish) darajasi", ["Ko'p", "O'rta", "Kam"], "Jismoniy faolllik"),
        q(12, "Siz uyda ertalabki badantarbiya qilasizmi?", ["Ha", "Yo'q", "Ba'zan"], "Jismoniy faolllik"),
        q(13, "Siz ochiq havoda piyoda sayr qilasizmi?", ["Har kuni 1 soatdan ko'p", "Muntazam ravishda 1 soatdan ko'p", "Sayr qilmayman"], "Jismoniy faolllik"),
        q(14, "Siz sport seksiyalariga borasizmi?", ["Ha", "Yo'q"], "Jismoniy faolllik"),
        q(15, "OTMda jismoniy mashg'ulotlar uchun sharoit mavjudmi?", ["Ha", "Yo'q"], "Jismoniy faolllik"),
        q(16, "Siz uyda jismoniy mashqlar bilan shug'ullanasizmi?", ["Ha", "Yo'q"], "Jismoniy faolllik"),
        q(17, "Jismoniy mashqlar bilan shug'ullanishga nima to'sqinlik qiladi?", ["Dangasalik", "Mablag' yetishmasligi", "O'quvdagi bandlik", "Mashg'ulot uchun sharoit yo'qligi"], "Jismoniy faolllik"),
        q(18, "O'z jismoniy faolligingizni qanday baholaysiz?", ["Yetarli", "Yetarli emas"], "Jismoniy faolllik"),
        q(19, "O'qish vaqtida asosan qanday holatda bo'lasiz?", ["Asosan o'tirib o'qiyman", "Asosan tik turaman yoki yuraman", "O'tirish va harakatni navbatma-navbat bajaraman"], "Jismoniy faolllik"),
        q(20, "Bo'sh vaqtingizda nima bilan shug'ullanasiz?", ["Gazeta, jurnal, adabiyot o'qiyman", "Teatr, kino, sport tadbirlari; oila va do'stlar bilan muloqot", "Jismoniy mashqlar, sport, piyoda sayr", "Televizor ko'raman", "Kompyuterda vaqt o'tkazaman"], "Jismoniy faolllik"),
        q(21, "Kuniga nechta soat uxlaysiz?", ["7 soatdan kam", "7 soatdan ko'p"], "Uyqu"),
        q(22, "Uxlab qolish qiyin bo'ladimi?", ["Ha", "Yo'q"], "Uyqu"),
        q(23, "Tunda uyg'onib ketmay uxlaysizmi?", ["Odatda ha", "Odatda yo'q"], "Uyqu"),
        q(24, "Tamaki iste'moli", ["Ha", "Yo'q", "Ilgari"], "Zararli odatlar"),
        q(25, "Alkogol iste'moli", ["Ha", "Yo'q", "Kamdan-kam"], "Zararli odatlar"),
        q(26, "Energetik ichimliklar iste'moli", ["Kundalik", "Haftada", "Kam", "Yo'q"], "Zararli odatlar"),
        q(27, "Ovqatlanish xarakteri", [], "Ovqatlanish", "matrix", MEAL_ROWS, MATRIX_FREQ_COLS, "Hafta davomida qayerda va qanchalik tez-tez ovqatlanasiz?"),
        q(28, "Quyidagi mahsulotlarni qanchalik tez-tez iste'mol qilasiz?", [], "Ovqatlanish", "matrix", FOOD_ROWS, MATRIX_FOOD_COLS),
        q(29, "Quyidagi preparatlarni qanchalik tez-tez qabul qilasiz?", [], "Ovqatlanish", "matrix", PREP_ROWS, MATRIX_PREP_COLS),
        q(30, "Fastfud iste'moli", ["Ko'p", "O'rta", "Kam", "Yo'q"], "Ovqatlanish"),
        q(31, "Suv iste'moli (kunlik)", ["1 litrdan kam", "1–2 litr", "2 litrdan ko'p"], "Ovqatlanish"),
        q(32, "O'z sog'lig'ingizni qanday baholaysiz?", ["Amalda sog'lomman", "Ba'zan o'tkir kasalliklarga chalinaman", "Tez-tez o'tkir kasalliklarga chalinaman", "Menda surunkali kasallik mavjud"], "Sog'liq holati"),
        q(33, "O'tgan yil davomida qancha marta kasallangansiz?", ["Kasallanmaganman", "1–2 marta", "3–5 marta", "5 martadan ko'p"], "Sog'liq holati"),
        q(34, "Kasallanganda qaysi usulni tanlaysiz?", ["Shifokorga murojaat qilaman", "O'zim mustaqil davo qilaman"], "Sog'liq holati"),
        q(35, "Dispanser ko'rigi uchun poliklinikaga borasizmi?", ["Ha", "Yo'q", "Ha, lekin muntazam emas"], "Sog'liq holati"),
        q(36, "Irsiy kasalliklar mavjudmi?", ["Ha", "Yo'q", "Bilmayman"], "Sog'liq holati"),
        q(37, "Quyidagi sog'liq bilan bog'liq shikoyatlar bezovta qiladimi?", [], "Sog'liq holati", "matrix", SYMPTOM_ROWS, ["Ha", "Yo'q"]),
        q(38, "Tayanch-harakat apparati holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(39, "Nafas olish tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(40, "Ovqat hazm qilish tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(41, "Yurak-qon tomir tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(42, "Endokrin tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(43, "Teri qoplamlari holati", ["Kasallik belgilari yo'q", "Belgilar bor, ammo tibbiy yordamga muhtoj emasman", "Kasallik mavjud"], "Sog'liq holati"),
        q(44, "Siydik-jinsiy tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(45, "Pastki oyoqlarda vena kengayishi", ["Ha", "Yo'q", "Bilmayman, tekshiruvga muhtojman"], "Sog'liq holati"),
        q(46, "Tana vazningizni qanday baholaysiz?", ["Normal", "Me'yordan yuqori", "Me'yordan past", "Javob berishga qiynalaman"], "Sog'liq holati"),
        q(47, "Tana vaznini qanchalik tez-tez o'lchaysiz?", ["Odatda o'lchamayman", "Yiliga 1 martadan ko'p emas", "Oyiga kamida 1 marta", "Haftasiga kamida 1 marta"], "Sog'liq holati"),
        q(48, "Ortiqcha vazn sog'liq uchun zararlimi?", ["Ha", "Yo'q", "Javob berishga qiynalaman"], "Sog'liq holati"),
        q(49, "Arterial bosimingizni nazorat qilasizmi?", ["Muntazam", "Faqat yomon his qilganda yoki shifokor ko'rigida"], "Sog'liq holati"),
        q(50, "Normal arterial bosim ko'rsatkichlari", ["110/70 dan past", "110/70 – 129/84", "130/85 – 139/89", "140/90 – 159/99", "160/100 – 179/109", "180/110 dan yuqori", "Bilmayman"], "Sog'liq holati"),
        q(51, "Arterial bosimning yuqori ko'tarilishi", ["Ha, tez-tez", "Ha, kamdan-kam", "Yo'q", "Bilmayman"], "Sog'liq holati"),
        q(52, "Normal bosimni saqlashga nima yordam beradi?", ["Ratsional ovqatlanish", "Suyuqlik miqdorini kamaytirish", "Dorilar", "Mehnat va dam olish tartibi", "Chekishni tashlash", "Alkogolni to'xtatish", "Yuqoridagilarning barchasi"], "Sog'liq holati"),
        q(53, "Qondagi glyukoza darajasi", ["3,5 mmol/l dan past", "3,3–5,5 mmol/l", "5,5 mmol/l dan yuqori", "Bilmayman"], "Sog'liq holati"),
        q(54, "Qondagi xolesterin darajasi", ["3,6 mmol/l dan past", "3,6–5 mmol/l", "5 mmol/l dan yuqori", "Bilmayman"], "Sog'liq holati"),
        q(55, "Chiniqish (zakalivanie) muolajalarini bajarasizmi?", ["Ha, har kuni", "Ba'zan", "Bajarmayman"], "Sog'liq holati"),
        q(56, "Sog'lom turmush tarzi haqida bilim darajangiz", ["Yuqori", "O'rta", "Past"], "Xabardorlik"),
        q(57, "Sog'lom turmush tarzi nimani anglatadi?", ["To'g'ri ovqatlanish", "Sport", "Zararli odatlardan voz kechish", "Barchasi"], "Xabardorlik"),
        q(58, "Sog'lom turmush tarzi haqida ma'lumotni qayerdan olasiz?", ["O'quv darslari", "Internet", "Ijtimoiy tarmoqlar", "Shifokorlar", "Oila / do'stlar"], "Ma'lumot manbalari"),
        q(59, "Eng ishonchli ma'lumot manbasi", ["Darsliklar", "Shifokorlar", "Internet", "Ilmiy maqolalar"], "Ma'lumot manbalari"),
        q(60, "Olingan bilimlarni hayotda qo'llaysizmi?", ["Doim", "Ba'zan", "Yo'q"], "Amaliyot"),
        q(61, "Bemorlarga sog'lom turmush tarzi bo'yicha tavsiya bera olasizmi?", ["Ha", "Qisman", "Yo'q"], "Amaliyot"),
        q(62, "Sog'lom turmush tarzini yaxshilash uchun takliflaringiz", [], "Qo'shimcha", "text"),
    ]
    return {
        "version": "2026-student",
        "title": "Talaba so'rovnomasi",
        "audience": "student",
        "totalQuestions": len(questions),
        "questions": questions,
    }


def build_pedagog():
    questions = [
        q(1, "Jinsingiz", ["Erkak", "Ayol"], "Umumiy qism"),
        q(2, "Yoshingiz", ["29 yoshgacha", "30–39 yosh", "40–49 yosh", "50–59 yosh", "60 yosh va undan katta"], "Umumiy qism"),
        q(3, "Oilaviy ahvolingiz", ["Bo'ydoq", "Uylangan / turmush qurgan", "Ajrashgan", "Beva qolgan"], "Umumiy qism"),
        q(4, "Farzandlar soni", ["Bolalar yo'q", "Bitta", "Ikkita", "Uch yoki undan ortiq"], "Umumiy qism"),
        q(5, "Doimiy yashash joyingiz", ["Shaharda", "Qishloqda"], "Umumiy qism"),
        q(6, "O'qitayotgan fan yo'nalishi", ["Nazariy", "Klinik", "Maxsus davolash–profilaktika", "Boshqa (ko'rsating)"], "Umumiy qism"),
        q(7, "Ishlayotgan lavozimingiz", ["Assistent", "Ma'ruzachi", "Katta o'qituvchi", "Dotsent", "Professor", "Kafedra mudiri", "O'qituvchi"], "Umumiy qism"),
        q(8, "Ilmiy darajangiz", ["Yo'q", "Fanlar nomzodi", "Fanlar doktori"], "Umumiy qism"),
        q(9, "Ilmiy unvoningiz", ["Yo'q", "Dotsent", "Professor"], "Umumiy qism"),
        q(10, "Dars beradigan talabalarning kursi", ["1-kurs", "2-kurs", "3-kurs", "4-kurs", "5-kurs", "6-kurs", "Malaka oshirish tinglovchilari", "Boshqa"], "Umumiy qism"),
        q(11, "Ish tajribangiz", ["3 yilgacha", "4–10 yil", "11–20 yil", "20 yildan ortiq"], "Umumiy qism"),
        q(12, "Yashash sharoitingiz", ["O'zingizga tegishli alohida kvartira (uy)", "Umumiy kvartirada o'z xonangiz", "Ijaraga olingan turar joy"], "Umumiy qism"),
        q(13, "Sog'lom turmush tarzi tushunchasi bilan tanishmisiz?", ["Ha", "Yo'q"], "Sog'lom turmush tarzi"),
        q(14, "Sog'lom turmush tarzining asosiy elementlari", ["Sog'lom ovqatlanish", "Yomon odatlardan voz kechish", "Jismoniy mashqlar va sport", "Mehnat va dam olish muvozanati", "Psixologik qulaylik", "Moddiy farovonlik", "Yuqoridagilarning barchasi"], "Sog'lom turmush tarzi", "multiple_choice"),
        q(15, "Kundalik hayotingizda sog'lom turmush tarzi elementlariga amal qilasizmi?", ["Ha", "Yo'q", "Qisman"], "Sog'lom turmush tarzi"),
        q(16, "Sog'lom turmush tarziga undaydigan asosiy istak", ["Sog'lom bo'lish", "Yaxshi ko'rinish", "Samarali ishlash", "Uzoq yashash"], "Sog'lom turmush tarzi"),
        q(17, "Sog'lom turmush tarzini olib bormaslik sababi", ["Xohlamayman", "Aniq tushunmayman", "Xohlayman, lekin amalga oshira olmayman"], "Sog'lom turmush tarzi"),
        q(18, "Ekologik omillar haqida ma'lumotingiz bormi?", ["Ha", "Yo'q"], "Sog'lom turmush tarzi"),
        q(19, "Irsiy omillar haqida ma'lumotingiz bormi?", ["Ha", "Yo'q"], "Sog'lom turmush tarzi"),
        q(20, "Sog'lig'ingizga g'amxo'rlik qilishi kerak", ["O'zim", "Tibbiyot xodimlari", "Oila a'zolarim", "Ish joyi ma'muriyati", "Yuqoridagilarning barchasi"], "Sog'lom turmush tarzi", "multiple_choice"),
        q(21, "Salomatlik haqida ma'lumotni qayerdan olgansiz?", ["Mutaxassislik o'rganishda", "Tibbiy muassasada", "Maxsus adabiyotlardan", "OAV va internetdan", "Qarindoshlar va do'stlardan"], "Sog'lom turmush tarzi", "multiple_choice"),
        q(22, "JSST sog'lom ovqatlanish tavsiyalari haqida tasavvuringiz bormi?", ["Ha", "Yo'q"], "Sog'lom turmush tarzi"),
        q(23, "Kasbiy bilimingiz JSST tavsiyalariga mos keladimi?", ["Ha", "Yo'q", "Qisman"], "Sog'lom turmush tarzi"),
        q(24, "TMI qanday hisoblashni bilasizmi?", ["Ha", "Yo'q"], "Sog'lom turmush tarzi"),
        q(25, "Bugungi kunda chekishga nima sabab?", ["Arzon sigaret tanlovi", "Moda", "Reklama", "Surunkali stress"], "Sog'lom turmush tarzi", "multiple_choice"),
        q(26, "Kompyuterda ishlash qoidalarini bilasizmi?", ["Ha", "Yo'q"], "Sog'lom turmush tarzi"),
        q(27, "Kasalliklarning oldini olish ma'lumotini qayerdan olish kerak?", ["Tibbiyot xodimlaridan", "OAV dan", "O'qish jarayonida", "Yuqoridagi barcha manbalardan"], "Sog'lom turmush tarzi"),
        q(28, "Dori-darmonlarni qanday xarid qilasiz?", ["Faqat shifokor ko'rsatmasi bo'yicha", "Reklamaga asoslanib", "Do'stlar maslahati bilan", "Yuqoridagi barcha manbalar bo'yicha"], "Hayot tarzi"),
        q(29, "Siz chekasizmi?", ["Ha", "Yo'q"], "Hayot tarzi"),
        q(30, "Kuniga nechta sigaret chekasiz?", ["1–10 ta", "11–20 ta", "20 tadan ortiq"], "Hayot tarzi"),
        q(31, "Chekish staji (yillarda)", ["5 yilgacha", "10 yilgacha", "20 yilgacha", "20 yildan ortiq"], "Hayot tarzi"),
        q(32, "Spirtli ichimliklarni iste'mol qilasizmi?", ["Har kuni", "Dam olish va bayram kunlarida", "Hech qachon iste'mol qilmayman"], "Hayot tarzi"),
        q(33, "Afzal ko'riladigan spirtli ichimlik", ["Kuchli ichimliklar", "Vino", "Pivo", "Kam alkogolli kokteyllar", "Energetik ichimliklar"], "Hayot tarzi"),
        q(34, "Giyohvand moddalardan foydalanasizmi?", ["Ha", "Yo'q"], "Hayot tarzi"),
        q(35, "Kun davomida ovqatni necha marta iste'mol qilasiz?", ["Bir marta", "Ikki marta", "Uch–to'rt marta", "To'rt martadan ortiq"], "Ovqatlanish"),
        q(36, "Ovqat tayyorlash uchun qaysi suvdan foydalanasiz?", ["Jo'mrak suvi", "Filtrlangan suv", "Shishaga solingan suv"], "Ovqatlanish"),
        q(37, "Kun davomida issiq ovqatni necha marta iste'mol qilasiz?", ["1 marta", "2–3 marta", "4–5 marta"], "Ovqatlanish"),
        q(38, "Uyda ovqat tayyorlashda qaysi yog'dan foydalanasiz?", ["O'simlik yog'i", "Hayvon yog'i", "Margarin", "Aralash turdagi yog'lar", "Boshqa (ko'rsating)"], "Ovqatlanish"),
        q(39, "Bir kunda qancha suyuqlik iste'mol qilasiz?", ["1,5–2 litr", "2 litrdan ko'p", "1 litr yoki undan kam", "Bilmayman"], "Ovqatlanish"),
        q(40, "Ovqatlanish xarakteri", [], "Ovqatlanish", "matrix", MEAL_ROWS, MATRIX_FREQ_COLS),
        q(41, "Quyidagi mahsulotlarni qanchalik tez-tez iste'mol qilasiz?", [], "Ovqatlanish", "matrix", FOOD_ROWS, MATRIX_FOOD_COLS),
        q(42, "Quyidagi preparatlarni qanchalik tez-tez qabul qilasiz?", [], "Ovqatlanish", "matrix", PREP_ROWS, MATRIX_PREP_COLS),
        q(43, "Uyda ertalabki badantarbiya qilasizmi?", ["Ha", "Yo'q", "Ba'zan"], "Jismoniy faolllik"),
        q(44, "Ochiq havoda piyoda sayr qilasizmi?", ["Har kuni 1 soatdan ko'p", "Muntazam ravishda 1 soatdan ko'p", "Sayr qilmayman"], "Jismoniy faolllik"),
        q(45, "Sport seksiyalariga borasizmi?", ["Ha", "Yo'q"], "Jismoniy faolllik"),
        q(46, "Ish joyida jismoniy mashg'ulotlar uchun sharoit mavjudmi?", ["Ha", "Yo'q"], "Jismoniy faolllik"),
        q(47, "Jismoniy mashqlar bilan shug'ullanishga nima to'sqinlik qiladi?", ["Dangasalik", "Mablag' yetishmasligi", "Ishdagi bandlik", "Mashg'ulot uchun sharoit yo'qligi"], "Jismoniy faolllik"),
        q(48, "Ish vaqtida asosan qanday holatda bo'lasiz?", ["Asosan o'tirib ishlayman", "Asosan tik turaman yoki yuraman", "O'tirish va harakatni navbatma-navbat bajaraman"], "Jismoniy faolllik"),
        q(49, "Bo'sh vaqtingizda nima bilan shug'ullanasiz?", ["Gazeta, jurnal, adabiyot o'qiyman", "Teatr, kino, sport; oila va do'stlar bilan muloqot", "Jismoniy mashqlar, sport, piyoda sayr", "Televizor ko'raman", "Kompyuterda vaqt o'tkazaman"], "Jismoniy faolllik"),
        q(50, "Kuniga nechta soat uxlaysiz?", ["7 soatdan kam", "7 soatdan ko'p"], "Uyqu"),
        q(51, "Uxlab qolish qiyin bo'ladimi?", ["Ha", "Yo'q"], "Uyqu"),
        q(52, "Tunda uyg'onib ketmay uxlaysizmi?", ["Odatda ha", "Odatda yo'q"], "Uyqu"),
        q(53, "O'z sog'lig'ingizni qanday baholaysiz?", ["Amalda sog'lomman", "Ba'zan o'tkir kasalliklarga chalinaman", "Tez-tez o'tkir kasalliklarga chalinaman", "Menda surunkali kasallik mavjud"], "Sog'liq holati"),
        q(54, "O'tgan yil davomida qancha marta kasallangansiz?", ["Kasallanmaganman", "1–2 marta", "3–5 marta", "5 martadan ko'p"], "Sog'liq holati"),
        q(55, "Kasallanganda qaysi usulni tanlaysiz?", ["Shifokorga murojaat qilaman", "O'zim mustaqil davo qilaman"], "Sog'liq holati"),
        q(56, "Dispanser ko'rigi uchun poliklinikaga borasizmi?", ["Ha", "Yo'q", "Ha, lekin muntazam emas"], "Sog'liq holati"),
        q(57, "Quyidagi sog'liq bilan bog'liq shikoyatlar bezovta qiladimi?", [], "Sog'liq holati", "matrix", SYMPTOM_ROWS, ["Ha", "Yo'q"]),
        q(58, "Tayanch-harakat apparati holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(59, "Nafas olish tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(60, "Ovqat hazm qilish tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(61, "Yurak-qon tomir tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(62, "Endokrin tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(63, "Teri qoplamlari holati", ["Kasallik belgilari yo'q", "Belgilar bor, ammo tibbiy yordamga muhtoj emasman", "Kasallik mavjud"], "Sog'liq holati"),
        q(64, "Siydik-jinsiy tizimi holati", ["Kasallik belgilari yo'q", "Belgilar bor, tekshiruvga muhtojman", "Kasallik mavjud"], "Sog'liq holati"),
        q(65, "Pastki oyoqlarda vena kengayishi", ["Ha", "Yo'q", "Bilmayman, tekshiruvga muhtojman"], "Sog'liq holati"),
        q(66, "Tana vazningizni qanday baholaysiz?", ["Normal", "Me'yordan yuqori", "Me'yordan past", "Javob berishga qiynalaman"], "Sog'liq holati"),
        q(67, "Ortiqcha vazn sog'liq uchun zararlimi?", ["Ha", "Yo'q", "Javob berishga qiynalaman"], "Sog'liq holati"),
        q(68, "Normal arterial bosim ko'rsatkichlari", ["110/70 dan past", "110/70 – 129/84", "130/85 – 139/89", "140/90 – 159/99", "160/100 – 179/109", "180/110 dan yuqori", "Bilmayman"], "Sog'liq holati"),
        q(69, "Arterial bosimning yuqori ko'tarilishi", ["Ha, tez-tez", "Ha, kamdan-kam", "Yo'q", "Bilmayman"], "Sog'liq holati"),
        q(70, "Normal bosimni saqlashga nima yordam beradi?", ["Ratsional ovqatlanish", "Suyuqlik miqdorini kamaytirish", "Dorilar", "Mehnat va dam olish tartibi", "Chekishni tashlash", "Alkogolni to'xtatish", "Yuqoridagilarning barchasi"], "Sog'liq holati"),
        q(71, "Qondagi glyukoza darajasi", ["3,5 mmol/l dan past", "3,3–5,5 mmol/l", "5,5 mmol/l dan yuqori", "Bilmayman"], "Sog'liq holati"),
        q(72, "Qondagi xolesterin darajasi", ["3,6 mmol/l dan past", "3,6–5 mmol/l", "5 mmol/l dan yuqori", "Bilmayman"], "Sog'liq holati"),
        q(73, "Kasbga oid professional kasallik mavjudmi?", ["Ha", "Yo'q", "Bilmayman"], "Sog'liq holati"),
        q(74, "Uyda ishlaysizmi?", ["Ha", "Yo'q"], "Mehnat sharoitlari"),
        q(75, "Kechasi ishlaysizmi?", ["Ha", "Yo'q"], "Mehnat sharoitlari"),
        q(76, "Ish kuni davomida 30 daqiqalik ovqatlanish tanaffusi bormi?", ["Ha", "Yo'q"], "Mehnat sharoitlari"),
        q(77, "Haqiqiy haftalik pedagogik yuklama", ["Haftasiga 36 soatdan ko'p", "Haftasiga 36 soatdan kam"], "Mehnat sharoitlari"),
        q(78, "Talabalar bilan qo'shimcha ishlash uchun ishda qolib ketasizmi?", ["Ha", "Yo'q"], "Mehnat sharoitlari"),
        q(79, "Asosiy ish joyingizdagi mehnat sharoitlari omillari", ["Havoning yuqori harorati", "Havoning past harorati", "Shamollatish", "Shovqin", "Vibratsiya", "Elektromagnit maydonlar", "Tabiiy yoritilishning yetishmasligi", "Ish joyining kam yoritilishi", "Og'ir yuklarni ko'tarish", "Uzoq vaqt diqqatni jamlash", "Emotsional zo'riqish", "Yuqumli kasalliklar xavfi", "O'quv yuklamasining oshib ketishi", "Dezinfeksiya vositalari bilan kontakt", "Majburiy noqulay ish holati", "Kompyuterda uzoq ishlash", "Yuqoridagilarning hech biri", "Boshqa (ko'rsating)"], "Mehnat sharoitlari", "multiple_choice"),
        q(80, "Ish vaqtida kayfiyat qanday?", ["Yaxshi", "Yomon"], "Mehnat sharoitlari"),
        q(81, "Professional kuyib ketish sindromi bormi?", ["Ha", "Yo'q"], "Mehnat sharoitlari"),
        q(82, "Ish joyida dam olish joylari mavjudmi?", ["Ha", "Yo'q"], "Mehnat sharoitlari"),
        q(83, "Ishda qayerda ovqatlanasiz?", ["Oshxonada (bufetda)", "Ish joyida", "Maxsus ajratilgan joyda", "Ishda ovqatlanmayman"], "Mehnat sharoitlari"),
        q(84, "Ishda odatda nima iste'mol qilasiz?", ["Buterbrodlar", "Tayyor sovuq taomlar", "Issiq taomlar", "Konder mahsulotlari", "Mevalar"], "Mehnat sharoitlari", "multiple_choice"),
        q(85, "Ishda olib kelgan ovqatni isitish imkoniyati bormi?", ["Ha", "Yo'q"], "Mehnat sharoitlari"),
        q(86, "Dietik ovqatlanishga muhtojmisiz?", ["Ha", "Yo'q"], "Mehnat sharoitlari"),
        q(87, "Bemorlarga sog'lom turmush tarzini tavsiya qilasizmi?", ["Ha", "Yo'q", "Ba'zan"], "Tibbiy profilaktika"),
        q(88, "Talabalarga sog'lom turmush tarzi bo'yicha tavsiyalar berasizmi?", ["Ha", "Yo'q", "Ba'zan"], "Tibbiy profilaktika"),
        q(89, "Tibbiy profilaktik ko'riklar foydalimi?", ["Ha, foydali", "Yo'q", "Foydali, lekin har doim samarali emas"], "Tibbiy profilaktika"),
        q(90, "So'nggi 3 yil ichida profilaktik tibbiy ko'rikdan o'tgansizmi?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
        q(91, "Profilaktik ko'rikda kasallik aniqlanganmi?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
        q(92, "Dispanserizatsiyadan o'tgansizmi?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
        q(93, "Ginekolog/urolog ko'rigiga qanchalik tez borasiz?", ["Yiliga kamida 1 marta", "Zarurat tug'ilganda", "Umuman bormayman"], "Tibbiy profilaktika"),
        q(94, "Stomatologga qanchalik tez murojaat qilasiz?", ["Yiliga 1–2 marta", "Yiliga 1 martadan kam", "Faqat tish og'rig'i bo'lsa", "Umuman bormayman"], "Tibbiy profilaktika"),
        q(95, "Muntazam emlash (vaksinatsiya)dan o'tasizmi?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
        q(96, "Infeksiyalar profilaktikasi qiziqtiradimi?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
        q(97, "Noinfeksion kasalliklar profilaktikasi qiziqtiradimi?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
        q(98, "Alimentar kasalliklar profilaktikasi qiziqtiradimi?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
        q(99, "Gipodinamiya kasalliklari profilaktikasi qiziqtiradimi?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
        q(100, "Hududiy salomatlik instituti faoliyati haqida xabardormisiz?", ["Ha", "Yo'q"], "Tibbiy profilaktika"),
    ]
    return {
        "version": "2026-pedagog",
        "title": "Pedagog so'rovnomasi",
        "audience": "pedagog",
        "totalQuestions": len(questions),
        "questions": questions,
    }


def main():
    for name, builder in [("student_survey", build_student), ("pedagog_survey", build_pedagog)]:
        schema = builder()
        path = DATA / f"{name}.json"
        path.write_text(json.dumps(schema, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"Wrote {path} ({schema['totalQuestions']} questions)")


if __name__ == "__main__":
    main()
